const bookMap = {
  genesis: "Genesis",
  exodus: "Exodus",
  leviticus: "Leviticus",
  numbers: "Numbers",
  deuteronomy: "Deuteronomy",
  joshua: "Joshua",
  judges: "Judges",
  ruth: "Ruth",
  "first samuel": "1 Samuel",
  "1 samuel": "1 Samuel",
  "second samuel": "2 Samuel",
  "2 samuel": "2 Samuel",
  "first kings": "1 Kings",
  "1 kings": "1 Kings",
  "second kings": "2 Kings",
  "2 kings": "2 Kings",
  "first chronicles": "1 Chronicles",
  "1 chronicles": "1 Chronicles",
  "second chronicles": "2 Chronicles",
  "2 chronicles": "2 Chronicles",
  ezra: "Ezra",
  nehemiah: "Nehemiah",
  esther: "Esther",
  job: "Job",
  psalms: "Psalms",
  psalm: "Psalms",
  proverbs: "Proverbs",
  ecclesiastes: "Ecclesiastes",
  "song of solomon": "Song of Solomon",
  "song of songs": "Song of Solomon",
  isaiah: "Isaiah",
  jeremiah: "Jeremiah",
  lamentations: "Lamentations",
  ezekiel: "Ezekiel",
  daniel: "Daniel",
  hosea: "Hosea",
  joel: "Joel",
  amos: "Amos",
  obadiah: "Obadiah",
  jonah: "Jonah",
  micah: "Micah",
  nahum: "Nahum",
  habakkuk: "Habakkuk",
  zephaniah: "Zephaniah",
  haggai: "Haggai",
  zechariah: "Zechariah",
  malachi: "Malachi",
  matthew: "Matthew",
  mark: "Mark",
  luke: "Luke",
  john: "John",
  acts: "Acts",
  romans: "Romans",
  "first corinthians": "1 Corinthians",
  "1 corinthians": "1 Corinthians",
  "second corinthians": "2 Corinthians",
  "2 corinthians": "2 Corinthians",
  galatians: "Galatians",
  ephesians: "Ephesians",
  philippians: "Philippians",
  colossians: "Colossians",
  "first thessalonians": "1 Thessalonians",
  "1 thessalonians": "1 Thessalonians",
  "second thessalonians": "2 Thessalonians",
  "2 thessalonians": "2 Thessalonians",
  "first timothy": "1 Timothy",
  "1 timothy": "1 Timothy",
  "second timothy": "2 Timothy",
  "2 timothy": "2 Timothy",
  titus: "Titus",
  philemon: "Philemon",
  hebrews: "Hebrews",
  james: "James",
  "first peter": "1 Peter",
  "1 peter": "1 Peter",
  "second peter": "2 Peter",
  "2 peter": "2 Peter",
  "first john": "1 John",
  "1 john": "1 John",
  "second john": "2 John",
  "2 john": "2 John",
  "third john": "3 John",
  "3 john": "3 John",
  jude: "Jude",
  revelation: "Revelation",
};

const numberWords = {
  zero: 0,
  one: 1,
  two: 2,
  three: 3,
  four: 4,
  five: 5,
  six: 6,
  seven: 7,
  eight: 8,
  nine: 9,
  ten: 10,
  eleven: 11,
  twelve: 12,
  thirteen: 13,
  fourteen: 14,
  fifteen: 15,
  sixteen: 16,
  seventeen: 17,
  eighteen: 18,
  nineteen: 19,
  twenty: 20,
  thirty: 30,
  forty: 40,
  fifty: 50,
  sixty: 60,
  seventy: 70,
  eighty: 80,
  ninety: 90,
  hundred: 100,
};

function parseNumber(word) {
  if (numberWords[word]) return numberWords[word];
  const num = parseInt(word);
  if (!isNaN(num)) return num;
  return null;
}

export function parseScripture(transcript) {
  const text = transcript.toLowerCase().replace(/[^\w\s]/g, " "); // remove punctuation
  const fillers = new Set([
    "turn",
    "with",
    "me",
    "to",
    "verse",
    "chapter",
    "book",
    "open",
    "read",
    "from",
    "the",
    "a",
    "an",
    "and",
    "or",
    "but",
    "in",
    "on",
    "at",
    "to",
    "for",
    "of",
    "with",
    "by",
    "let",
    "us",
    "go",
    "now",
    "here",
    "is",
    "that",
    "this",
    "it",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "being",
    "have",
    "has",
    "had",
    "do",
    "does",
    "did",
    "will",
    "would",
    "can",
    "could",
    "should",
    "may",
    "might",
    "must",
    "shall",
    "let",
    "us",
    "i",
    "you",
    "he",
    "she",
    "we",
    "they",
    "them",
    "their",
    "our",
    "my",
    "your",
    "his",
    "her",
    "its",
    "our",
    "your",
    "their",
  ]);
  const words = text.split(/\s+/).filter((w) => w && !fillers.has(w));

  // find book
  let book = null;
  let startIndex = 0;
  for (let len = 1; len <= words.length; len++) {
    const candidate = words.slice(0, len).join(" ");
    if (bookMap[candidate]) {
      book = bookMap[candidate];
      startIndex = len;
      break;
    }
  }
  if (!book) return null;

  // remaining words
  const remaining = words.slice(startIndex);
  const nums = remaining.map(parseNumber).filter((n) => n !== null);
  if (nums.length < 2) return null;
  const chapter = nums[0];
  const verse = nums[1];
  return { book, chapter, verse };
}
